import { getBasePath } from '../../service'

export const NAME = 'Auth'
export const entryPoint = `${getBasePath()}/api/auth`
export const types = {
  SHOW_ERROR: `${NAME}SHOW_ERROR`,
  LOGIN_REQUEST: `${NAME}LOGIN_REQUEST`,
  LOGIN_SUCCESS: `${NAME}LOGIN_SUCCESS`,
  LOGIN_FAILURE: `${NAME}LOGIN_FAILURE`,
  SIGNUP_REQUEST: `${NAME}SIGNUP_REQUEST`,
  SIGNUP_SUCCESS: `${NAME}SIGNUP_SUCCESS`,
  SIGNUP_FAILURE: `${NAME}SIGNUP_FAILURE`,
  RESTORE_REQUEST: `${NAME}RESTORE_REQUEST`,
  RESTORE_SUCCESS: `${NAME}RESTORE_SUCCESS`,
  RESTORE_FAILURE: `${NAME}RESTORE_FAILURE`
}
